server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            ## REST CLIENT -> http://localhost:8080/auth/login
            ## API GATEWAY -> http://auth-service:8080/login
            ## AUTH SERVICE (SPRING BOOT APP) -> /login -> Token

            - id: auth-service-route
              uri: http://auth-service:8080
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            ## REST CLIENT -> http://localhost:8080/api/patients
            ## API GATEWAY -> http://patient-service:8080/patients
            ## PATIENT SERVICE (SPRING BOOT APP) -> /patients -> Patients Array
            - id: patient-service-route
              uri: http://patient-service:8080
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1
                - TokenValidation

            ## REST CLIENT -> http://localhost:8080/api-docs/patients
            ## API GATEWAY -> http://patient-service:8080/v3/api-docs
            - id: api-docs-patient-route
              uri: http://patient-service:8080
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients,/v3/api-docs
                - TokenValidation
            - id: api-docs-auth-route

              uri: http://auth-service:8080
              predicates:
                - Path=/api-docs/auth
              filters:
                - RewritePath=/api-docs/auth,/v3/api-docs
